# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craftbit < Formula
  desc "Bitcoin Swiss Army Knife 🪛 🌕 🔧"
  homepage "https://www.stackzoo.io/"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stackzoo/craftbit/releases/download/v0.0.7/craftbit_0.0.7_darwin_arm64.tar.gz"
      sha256 "57bc0e684b96567418ed8418d9ff919fc38ac00c19b7ca71000c9767f99aa0b3"

      def install
        bin.install "craftbit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stackzoo/craftbit/releases/download/v0.0.7/craftbit_0.0.7_darwin_amd64.tar.gz"
      sha256 "5749b4d44c8102990f246f2ebdb18225059e41bcca76f122f5bd254508857ba2"

      def install
        bin.install "craftbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stackzoo/craftbit/releases/download/v0.0.7/craftbit_0.0.7_linux_amd64.tar.gz"
      sha256 "291d740b4f55b368e7cd41880f5eaeddc8e1dfff2bda60a80266360fc3bb05f1"

      def install
        bin.install "craftbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stackzoo/craftbit/releases/download/v0.0.7/craftbit_0.0.7_linux_arm64.tar.gz"
      sha256 "10d8a5471c13a556b1e2e2f49d96cad23f8e0e3b128185686fe2e103a3ec4a12"

      def install
        bin.install "craftbit"
      end
    end
  end

  def caveats
    <<~EOS
      Launch and have fun
    EOS
  end
end
