# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craftbit < Formula
  desc "Bitcoin Swiss Army Knife 🪛 🌕 🔧"
  homepage "https://example.com/"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stackzoo/craftbit/releases/download/v0.0.6/craftbit_0.0.6_darwin_amd64.tar.gz"
      sha256 "03ad71f77865ffccd87342fd883e269a5fc3faf97f9fb764315c0ab6e9877088"

      def install
        bin.install "craftbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stackzoo/craftbit/releases/download/v0.0.6/craftbit_0.0.6_darwin_arm64.tar.gz"
      sha256 "c1e0650ba8134e92eac5525d54296d64c9684ccc2b192e11081d07a84f4554a0"

      def install
        bin.install "craftbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stackzoo/craftbit/releases/download/v0.0.6/craftbit_0.0.6_linux_arm64.tar.gz"
      sha256 "5f764931db0acc49fb87c3727c17b5c699d4e68e6449e179a5d0ed1b5a9f7dae"

      def install
        bin.install "craftbit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stackzoo/craftbit/releases/download/v0.0.6/craftbit_0.0.6_linux_amd64.tar.gz"
      sha256 "783765ca90150b845426163d21c5b480bb6a792e5d46c123e5246679c03c77d5"

      def install
        bin.install "craftbit"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
