# .goreleaser.yaml
brews:
  -
    name: craftbit

    url_template: "https://github.com/stackzoo/craftbit/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: r3drun3
      email: simone.ragonesi@stackzoo.io

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula

    caveats: "Launch and have fun"

    homepage: "https://www.stackzoo.io/"

    description: "Bitcoin Swiss Army Knife 🪛 🌕 🔧"

    license: "MIT"

    repository:
      owner: stackzoo
      name: craftbit
      branch: main
      pull_request:
        enabled: true
        draft: true
