name: CI

on:
  #schedule:
    #- cron: '0 0 */15 * *' # uncomment this schedule to run at midnight every 15 day of every months
  push:
    paths:
      - '**'
      - '!README.md'
      - '!**/.gitignore'
      - '!**/Dockerfile'
      - '!**/LICENSE'

jobs:
  lint-and-goaction:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Lint Go Code
        run: go vet ./...